/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "import",
            "endpoint": "https://3gmu03bzh1.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "transactionReceiverAPI",
            "endpoint": "https://7m9y16xnsa.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "Payment",
            "endpoint": "https://qpyx2epl86.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "balanceSheet",
            "endpoint": "https://8gc5om0at7.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "manual",
            "endpoint": "https://eiihxat7xl.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "wallet",
            "endpoint": "https://cu7ikg9npk.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:f9cf5742-ff87-4acf-802e-e5c541316ef4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_0pdKsztOH",
    "aws_user_pools_web_client_id": "10blr7o6m6dl3i161h88nctenl",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-amplifyd57e18f042f24-staging-00044-deployment",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
